### PR TITLE
Open graph support

### PR DESCRIPTION
**Pull request by Nirmitjatana**
This PR is a continuation of upptime/upptime#374.
It adds all the major open graph tags including title, description, image etc

### CODE REVIEW

**Comment by Nirmitjatana** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Nirmitjatana** [comment]
**recheck**

**Comment by Nirmitjatana** [comment]
@AnandChowdhary have a look, Thanks!

**Comment by AnandChowdhary** [comment]
The quotes are wrong, you're using `”` instead of HTML's `"` in this PR.

Also, I think the OG data should be specific to the Upptime repo, right? The name and the icon of the project, not of Upptime, is more appropriate. Happy to discuss!

**Comment by Nirmitjatana** [comment]
@AnandChowdhary We have a single status page for n number of projects, So generalizing it with upptime's info should make sense.
Or
We can take the ``` introTitle ``` and ```introMessage``` provided by the user in ``` upptimerc.yml``` and use it as OG data.

**Comment by AnandChowdhary** [comment]
> We can take the introTitle and introMessage provided by the user in upptimerc.yml and use it as OG data.

Yep, that's exactly what I mean! :)

**Pull request closed without merging**
