### PR TITLE
Add support for upptime/uptime-monitor#221

### PR DESCRIPTION
**Pull request by Andre601**
This PR is for adding support for upptime/uptime-monitor#221

As with the other PR do I have no real experience with svelte here... So if what I did is wrong let me know with the right solution. Thanks.

### CODE REVIEW

**Comment by Andre601** [comment]
.

**Comment by Andre601** [comment]
I give up....

The fact that even PRs get marked as stale is so BS to have.

I won't react to the next stale notice.
Hopefully there won't be any, but I doubt this in all honesty...

**Comment by AnandChowdhary** [comment]
I'm sorry you feel this way, but I don't understand, this is a draft PR, right? So there's nothing actionable by me... or is it ready for review and it's on me?

**Comment by Andre601** [comment]
I left it as a PR as I first wanted feedback on if this is a good aproach on adding what I suggested in https://github.com/upptime/upptime/discussions/569 and https://github.com/upptime/upptime/discussions/572

I can turn it into a normal PR. Tho, I can't tell if either this or https://github.com/upptime/uptime-monitor/pull/221 would need to be implemented first... Don't know the exact dependency relations between these two.

**Pull request closed without merging**
