### PR TITLE
Fixes moving of assets to gh-pages branch

### PR DESCRIPTION
**Pull request by Nirmitjatana**
This tween should fix the issue upptime/upptime#256

### CODE REVIEW

**Comment by Nirmitjatana** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Nirmitjatana** [comment]
recheck

**Comment by Nirmitjatana** [comment]
@AnandChowdhary can you have a look?
Thanks!

**Comment by Nirmitjatana** [comment]
recheck

**Comment by AnandChowdhary** [comment]
Thanks!

**Pull request merged**
